server:
  port: 8080

# example values
indexing-settings:
  sites:
    - url: https://www.playback.ru/
      name: PlayBack.Ru
      id: 1
    - url: https://skillbox.ru/
      name: Skill box
      id: 2
    - url: https://dombulgakova.ru/
      name: Дом Булгакова
      id: 3


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&serverTimezone=UTC
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
